# Generated by Django 4.0.1 on 2022-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyestateapp', '0002_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение в середине статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Начало статьи'),
        ),
    ]
