# Generated by Django 4.0.1 on 2022-02-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyestateapp', '0003_article_image1_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text1',
            field=models.TextField(default=' ', verbose_name='Окончание статьи'),
        ),
    ]
