# Generated by Django 4.0.1 on 2022-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyestateapp', '0004_article_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='period',
            field=models.CharField(default=' ', max_length=100, verbose_name='Название статьи'),
        ),
    ]
