# Generated by Django 4.0.1 on 2022-02-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyestateapp', '0005_article_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text10',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text11',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text12',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text13',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text14',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text15',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text16',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text17',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text18',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text19',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text2',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text20',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text21',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text22',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text23',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text24',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text25',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text26',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text27',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text28',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text29',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text3',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text30',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text31',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text32',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text33',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text34',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text35',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text36',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text4',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text5',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text6',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text7',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text8',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text9',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='period',
            field=models.CharField(default=' ', max_length=100, verbose_name='Период рождения'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text1',
            field=models.TextField(default=' ', verbose_name='Продолжение статьи'),
        ),
    ]
