# Generated by Django 4.0.1 on 2022-02-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyestateapp', '0007_article_period1_article_period2_article_period3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='period1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Влияние: '),
        ),
        migrations.AlterField(
            model_name='article',
            name='period2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Символы: '),
        ),
        migrations.AlterField(
            model_name='article',
            name='period3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цвета:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='period4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Камни:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='period5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Металл:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='period6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Талисман:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='period7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Благоприятные числа:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text1',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text10',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 10'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text11',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 11'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text12',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 12'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text13',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 13'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text14',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 14'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text15',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 15'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text16',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 16'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text17',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 17'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text18',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 18'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text19',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 19'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text20',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 20'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text21',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 21'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text22',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 22'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text23',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 23'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text24',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 24'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text25',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 25'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text26',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 26'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text27',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 27'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text28',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 28'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text29',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 29'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text30',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 30'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text31',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 31'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text32',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 32'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text33',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 33'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text34',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 34'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text35',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 35'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text36',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 36'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text4',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text5',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text6',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 6'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text7',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 7'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text8',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 8'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text9',
            field=models.TextField(blank=True, verbose_name='Продолжение статьи 9'),
        ),
    ]
