# Generated by Django 4.0.1 on 2022-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyestateapp', '0008_alter_article_period1_alter_article_period2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение в середине статьи'),
        ),
    ]
